#! /bin/bash
set -e

network_name=$(python -c "import name; print(name.network_name)")

floyd init cifar10/$network_name/train

data_output_id=$(cat floyd/ids.yml | shyaml get-value data.output)
floyd run \
  --gpu \
  --env tensorflow:py2 \
  --data $data_output_id:data \
  "DATAGET_HOME=/data MODEL_PATH=/output python train.py"
